model: # the parameter of model
  base_learning_rate: 1e-6
  target: specvqgan.models.vqgan.VQModel
  params:
    embed_dim: 256 # 每个embedding的维度
    n_embed: 128 # 有多少个embedding previous 256
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 848
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [53]
      dropout: 0.0

    lossconfig:
      target: specvqgan.modules.losses.vqperceptual.VQLPAPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 60001
        disc_weight: 0.8
        codebook_weight: 1.0
        min_adapt_weight: 1.0
        max_adapt_weight: 1.0
        perceptual_weight: 1.0

lightning:
  callbacks:
    image_logger:
      target: train.ImageLogger
      params:
        for_specs: True
        vocoder_cfg:
          target: train.VocoderMelGan
          params:
            ckpt_vocoder: 'Codebook/vocoder_audioset/logs/audioset/'
  trainer:
    sync_batchnorm: true

data:
  target: train.SpectrogramDataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 12

    spec_dir_path: '/data/audioset/features/*/melspec_10s_22050hz'
    sample_rate: 22050
    mel_num: 80
    spec_len: 860
    spec_crop_len: 848 # previous work, we use 848
    random_crop: False

    train:
      target: specvqgan.data.audioset.VASSpecsTrain
      params:
        specs_dataset_cfg:
          split_path: 'Codebook/data/audioset/txt/audioset_train.txt'
    validation:
      target: specvqgan.data.audioset.VASSpecsValidation
      params:
        specs_dataset_cfg:
          split_path: 'Codebook/data/audioset/txt/audioset_valid.txt'
